describe('Payslip Generator', () => {

  beforeEach(() => {
    cy.visit('https://qa.platoonco.com/')
    cy.get('a[href="/payslip-generator"]')
      .should('be.visible')
      .eq(2)
      .click()
  })

 it('Payslip Generator core works', () => {
    cy.url()
      .should('include', '/payslip-generator')
    cy.get('#company-name')
      .clear()
      .type('QA Test')
    cy.get('#company-address')
      .type('123, QA Lane')
    cy.get('#employee-name')
      .clear()
      .type('Quality Assurance')
    cy.get('#job-title')
      .clear()
      .type('QA Engineer')
    cy.get('#employee-id')
      .type('emp-101')

    cy.get('input[id="pay-period"]')
      .should('be.visible')
      .click({force:true})

    cy.get('input[id="payment-date"]')
 

    cy.get('input[value="Basic Salary"]')
      .clear()
      .type('Basic')
    cy.get('input[value="250,000.00"]')
      .clear()
      .type('400,000.00')
    cy.get('input[value="Transport Allowance"]')
      .clear()
      .type('Wardobe Alowance')
    cy.get('input[value="25,000.00"]')
      .clear()
      .type('40,000.00')
    cy.contains('Add earning')
      .should('be.visible')
      .click()
    cy.get('input[placeholder="Label"]')
      .eq('2')
      .type('Transport Allowance')
    cy.get('input[placeholder="0.00"]')
      .eq('2')
      .type('60,000.00')
    cy.get('input[value="Pension (8%)"]')
      .clear()
      .type('One-time Lateness')
    cy.get('input[placeholder="0.00"]')
      .eq('3')
      .clear()
      .type('5,000.00')
    cy.get('input[value="PAYE Tax"]')
      .clear()
      .type('Pension')
    cy.get('input[placeholder="0.00"]')
      .eq('4')
      .clear()
      .type('30,000.00')
    cy.contains('Add deduction')
      .should('be.visible')
      .click()
    cy.get('input[placeholder="Label"]')
      .eq('5')
      .type('PAYE tax')
    cy.get('input[placeholder="0.00"]')
      .eq('5')
      .type('45,000.00')

    cy.get('.no-print button')
      .contains('Download Payslip')
      .click()
    
    cy.contains('Preparing')
      .should('be.visible')
 })

 it('Pricing button on this page works', ()=> {
     cy.contains('See Growth pricing')
       .should('be.visible')
       .click()
     cy.url()
       .should('include', '/pricing')
  })

})