describe('Payroll Pending & Approval Flow', () => {
    
  beforeEach(() => {
    cy.login()
    cy.get('a[href="/dashboard/payroll"]', {timeout: 10000})
      .should('be.visible')
      .click({force: true})  
    cy.url()
      .should('include', '/dashboard/payroll/history')
    cy.contains('Pending Payroll')
      .click({force: true})
    cy.url()
      .should('include', '/dashboard/payroll/pending')
  })

  it('shows an error if disbursement time is not set', () => {
    cy.get('button')
      .contains('Approve')
      .first()
      .click({force:true})
    cy.contains('Error')
      .should('be.visible')
  })

  it('successfully updates payroll send date/time and allows approval', () => {
    cy.get('button')
      .contains('Settings')
      .first()
      .click({force:true})
    cy.get('#payrollSendTime')
      .click({force:true})
    cy.contains('12:00 AM')
      .click({force:true}) 
    cy.get('#payrollSendDate')
      .click({force:true})
    cy.contains('30')
      .click({force:true})
    cy.get('button')
      .contains('Save')
        .click({force:true})
    cy.contains('Payout time updated successfully')
      .should('be.visible')
    cy.get('button')
      .contains('Approve')
      .first()
      .click({force:true})
    cy.contains('Payroll Approved')
      .should('be.visible')
  })

  it('confirms that the payroll decline button functions properly', () => {
    cy.get('button')
      .contains('Decline')
      .first()
      .click({force:true})
      .contains('Payroll Declined')
      .should('be.visible')
    })
})