name: Scheduled Cypress E2E Tests

on:
  schedule:
    - cron: "0 7 * * *"
  # Manual Trigger
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Cypress Tests on Scheduled Cron
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          # Use the EXACT plain text name you created in GitHub Settings, NOT the raw uuid key itself
          CYPRESS_RECORD_KEY: ${{ secrets.cab72095-760a-46fc-8f7b-471075b8b7d8 }}
